Lab-3/django_project/course_management/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('asignaturas/', views.asignaturas_list, name='asignaturas_list'),
    path('asignaturas/<int:pk>/', views.asignatura_detail, name='asignatura_detail'),
    path('alumnos/', views.alumnos_list, name='alumnos_list'),
    path('alumnos/<int:pk>/', views.alumno_detail, name='alumno_detail'),
    path('agregar_alumno/', views.agregar_alumno, name='agregar_alumno'),
    path('agregar_asignatura/', views.agregar_asignatura, name='agregar_asignatura'),
        path('alumnos/<int:pk>/editar/', views.editar_alumno, name='editar_alumno'),
    path('alumnos/<int:pk>/eliminar/', views.eliminar_alumno, name='eliminar_alumno'),
]

Lab-3/django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("course_management.urls")),
]

Lab-3/django_project/course_management/models.py
from django.db import models

class Asignatura(models.Model):
    nombre = models.CharField(max_length=100)
    codigo = models.CharField(max_length=20, unique=True,default="")

    def __str__(self):
        return f"{self.codigo} - {self.nombre}"

class Alumno(models.Model):
    nombre = models.CharField(max_length=100)
    apellido_paterno = models.CharField(max_length=100, default="")
    apellido_materno = models.CharField(max_length=100,default="")
    fecha_nacimiento = models.DateField(null=True)
    asignaturas = models.ManyToManyField(Asignatura)

    def __str__(self):
        return f"{self.nombre} {self.apellido_paterno} {self.apellido_materno}"

Lab-3/django_project/course_management/forms.py
from django import forms
from .models import Alumno, Asignatura

class AlumnoForm(forms.ModelForm):
    asignaturas = forms.ModelMultipleChoiceField(
        queryset=Asignatura.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Alumno
        fields = '__all__'

class AsignaturaForm(forms.ModelForm):
    alumnos = forms.ModelMultipleChoiceField(
        queryset=Alumno.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False  # Opcional, dependiendo de tus requerimientos
    )

    class Meta:
        model = Asignatura
        fields = ['nombre', 'codigo', 'alumnos']

class AlumnoDeleteForm(forms.Form):
    alumno_a_eliminar = forms.ModelChoiceField(
        queryset=Alumno.objects.all(),
        widget=forms.RadioSelect,
        empty_label=None,
    )

Lab-3/django_project/course_management/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Asignatura, Alumno
from .forms import AlumnoForm, AsignaturaForm, AlumnoDeleteForm

def index(request):
    # Obtén la lista de asignaturas
    asignaturas = Asignatura.objects.all()

    # Calcula la cantidad de alumnos para cada asignatura
    asignaturas_con_alumnos = []
    for asignatura in asignaturas:
        cantidad_alumnos = Alumno.objects.filter(asignaturas=asignatura).count()
        asignaturas_con_alumnos.append({
            'asignatura': asignatura,
            'cantidad_alumnos': cantidad_alumnos,
        })

    # Configura las migas de pan
    breadcrumbs = [{'text': 'Home', 'url': '/'}]

    # Renderiza la plantilla y pasa los datos al contexto
    return render(request, 'index.html', {'asignaturas_con_alumnos': asignaturas_con_alumnos, 'breadcrumbs': breadcrumbs})

def asignaturas_list(request):
    breadcrumbs = [{'text': 'Home', 'url': '/'}, {'text': 'Asignaturas', 'url': '/asignaturas/'}]
    asignaturas = Asignatura.objects.all()
    return render(request, 'asignaturas_list.html', {'asignaturas': asignaturas, 'breadcrumbs': breadcrumbs})

def asignatura_detail(request, pk):
    breadcrumbs = [{'text': 'Home', 'url': '/'}, {'text': 'Asignaturas', 'url': '/asignaturas/'}, {'text': 'Detalle de Asignatura', 'url': '/asignaturas/{}/'.format(pk)}]
    asignatura = get_object_or_404(Asignatura, pk=pk)
    return render(request, 'asignatura_detail.html', {'asignatura': asignatura, 'breadcrumbs': breadcrumbs})

def alumnos_list(request):
    breadcrumbs = [{'text': 'Home', 'url': '/'}, {'text': 'Alumnos', 'url': '/alumnos/'}]
    alumnos = Alumno.objects.all()
    form = AlumnoDeleteForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        alumno_a_eliminar = form.cleaned_data['alumno_a_eliminar']
        alumno = get_object_or_404(Alumno, pk=alumno_a_eliminar.pk)
        alumno.delete()
        return redirect('alumnos_list')

    return render(request, 'alumnos_list.html', {'alumnos': alumnos, 'form': form, 'breadcrumbs': breadcrumbs})

def alumno_detail(request, pk):
    breadcrumbs = [{'text': 'Home', 'url': '/'}, {'text': 'Alumnos', 'url': '/alumnos/'}, {'text': 'Detalle de Alumno', 'url': '/alumnos/{}/'.format(pk)}]
    alumno = get_object_or_404(Alumno, pk=pk)
    return render(request, 'alumno_detail.html', {'alumno': alumno, 'breadcrumbs': breadcrumbs})


def agregar_alumno(request):
    if request.method == 'POST':
        form = AlumnoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('alumnos_list')  # Redirigir a la página de lista de alumnos
    else:
        form = AlumnoForm()
    
    breadcrumbs = [{'text': 'Home', 'url': '/'}, {'text': 'Alumnos', 'url': '/alumnos/'}, {'text': 'Agregar Alumno', 'url': '/agregar_alumno/'}]
    return render(request, 'agregar_alumno.html', {'form': form, 'breadcrumbs': breadcrumbs})


def agregar_asignatura(request):
    if request.method == 'POST':
        form = AsignaturaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('asignaturas_list')  # Redirige a la lista de asignaturas
    else:
        form = AsignaturaForm()
    breadcrumbs = [{'text': 'Home', 'url': '/'}, {'text': 'Asignaturas', 'url': '/asignaturas/'}, {'text': 'Agregar Asignatura', 'url': '/agregar_asignatura/'}]
    return render(request, 'agregar_asignatura.html', {'form': form, 'breadcrumbs': breadcrumbs})

#Eliminar/Editar Alumnos
def editar_alumno(request, pk):
    alumno = get_object_or_404(Alumno, pk=pk)
    
    if request.method == 'POST':
        form = AlumnoForm(request.POST, instance=alumno)
        if form.is_valid():
            form.save()
            return redirect('alumnos_list')
    else:
        form = AlumnoForm(instance=alumno)
    
    return render(request, 'editar_alumno.html', {'form': form, 'alumno': alumno})

def eliminar_alumno(request, pk):
    alumno = get_object_or_404(Alumno, pk=pk)
    
    if request.method == 'POST':
        alumno.delete()
        return redirect('alumnos_list')
    
    return render(request, 'eliminar_alumno.html', {'alumno': alumno})

Lab-3/django_project/templates/agregar_alumno.html
<!DOCTYPE html>

<html>
<head>
    
    <title>Agregar Alumno</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/breadcrumbs.css' %}">
</head>
<body>

    <h1>Agregar Alumno</h1>
    <div class="breadcrumbs">
        <ul>
            {% for breadcrumb in breadcrumbs %}
                <li><a href="{{ breadcrumb.url }}">{{ breadcrumb.text }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
</body>
</html>

Lab-3/django_project/templates/agregar_asignatura.html
<!-- agregar_asignatura.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Agregar Asignatura</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/breadcrumbs.css' %}">
</head>
<body>
    <h1>Agregar Asignatura</h1>
    <div class="breadcrumbs">
        <ul>
            {% for breadcrumb in breadcrumbs %}
                <li><a href="{{ breadcrumb.url }}">{{ breadcrumb.text }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
</body>
</html>

Lab-3/django_project/templates/alumno_detail.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Detalles de Alumno</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/breadcrumbs.css' %}">
</head>
<body>

    <h1>Detalles de Alumno</h1>
    <div class="breadcrumbs">
        <ul>
            {% for breadcrumb in breadcrumbs %}
                <li><a href="{{ breadcrumb.url }}">{{ breadcrumb.text }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <p>Nombre: {{ alumno.nombre }}</p>
    <p>Apellido Paterno: {{ alumno.apellido_paterno }}</p>
    <p>Apellido Materno: {{ alumno.apellido_materno }}</p>
    <p>Fecha de Nacimiento: {{ alumno.fecha_nacimiento }}</p>
    <h2>Asignaturas inscritas:</h2>
    <ul>
        {% for asignatura in alumno.asignaturas.all %}
            <li>{{ asignatura.codigo }} - {{ asignatura.nombre }}</li>
        {% endfor %}
    </ul>
</body>
</html>

Lab-3/django_project/templates/alumnos_list.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Lista de Alumnos</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/breadcrumbs.css' %}">
</head>
<body>

    <h1>Lista de Alumnos</h1>
    
    <div class="breadcrumbs">
        <ul>
            {% for breadcrumb in breadcrumbs %}
                <li><a href="{{ breadcrumb.url }}">{{ breadcrumb.text }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Apellido Paterno</th>
                <th>Apellido Materno</th>
                <th>Fecha de Nacimiento</th>
                <th>Acciones</th> <!-- Nueva columna para acciones -->
            </tr>
        </thead>
        <tbody>
            {% for alumno in alumnos %}
                <tr>
                    <td>{{ alumno.nombre }}</td>
                    <td>{{ alumno.apellido_paterno }}</td>
                    <td>{{ alumno.apellido_materno }}</td>
                    <td>{{ alumno.fecha_nacimiento }}</td>
                    <td>
                        <a href="{% url 'editar_alumno' alumno.pk %}">Editar</a> |
                        <a href="{% url 'eliminar_alumno' alumno.pk %}">Eliminar</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

Lab-3/django_project/templates/asignatura_detail.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Detalles de Asignatura</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/breadcrumbs.css' %}">
</head>
<body>

    <h1>Detalles de Asignatura</h1>
    <div class="breadcrumbs">
        <ul>
            {% for breadcrumb in breadcrumbs %}
                <li><a href="{{ breadcrumb.url }}">{{ breadcrumb.text }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <p>Nombre: {{ asignatura.nombre }}</p>
    <p>Código: {{ asignatura.codigo }}</p>
    <h2>Alumnos inscritos:</h2>
    <ul>
        {% for alumno in asignatura.alumno_set.all %}
            <li>{{ alumno.nombre }} {{ alumno.apellido_paterno }} {{ alumno.apellido_materno }}</li>
        {% endfor %}
    </ul>
</body>
</html>

Lab-3/django_project/templates/asignaturas_list.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Lista de Asignaturas</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/breadcrumbs.css' %}">
</head>
<body>
    <h1>Lista de Asignaturas</h1>
    <div class="breadcrumbs">
        <ul>
            {% for breadcrumb in breadcrumbs %}
                <li><a href="{{ breadcrumb.url }}">{{ breadcrumb.text }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <ul>
        {% for asignatura in asignaturas %}
            <li><a href="{% url 'asignatura_detail' asignatura.pk %}">{{ asignatura.nombre }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

Lab-3/django_project/templates/editar_alumno.html
<!-- editar_alumno.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Editar Alumno</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/breadcrumbs.css' %}">
</head>
<body>
    <h1>Editar Alumno</h1>
    <div class="breadcrumbs">
        <ul>
            {% for breadcrumb in breadcrumbs %}
                <li><a href="{{ breadcrumb.url }}">{{ breadcrumb.text }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar Cambios</button>
    </form>

    <a href="{% url 'alumnos_list' %}">Volver a la Lista de Alumnos</a>
</body>
</html>

Lab-3/django_project/templates/eliminar_alumno.html
<!-- eliminar_alumno.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Eliminar Alumno</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/breadcrumbs.css' %}">
</head>
<body>
    <h1>Eliminar Alumno</h1>
    <div class="breadcrumbs">
        <ul>
            {% for breadcrumb in breadcrumbs %}
                <li><a href="{{ breadcrumb.url }}">{{ breadcrumb.text }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <p>¿Estás seguro de que deseas eliminar al alumno "{{ alumno }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit">Eliminar</button>
    </form>

    <a href="{% url 'alumnos_list' %}">Cancelar</a>
</body>
</html>

Lab-3/django_project/templates/index.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Página de Inicio</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/breadcrumbs.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/tabla.css' %}">
</head>
<body>
    <h1>Bienvenido a la Gestión de Asignaturas y Alumnos</h1>
    <div class="breadcrumbs">
        <ul>
            {% for breadcrumb in breadcrumbs %}
                <li><a href="{{ breadcrumb.url }}">{{ breadcrumb.text }}</a></li>
            {% endfor %}
        </ul>
    </div>

    <table class="table table-borderless">
        <thead>
            <tr>
                <th>Asignatura</th>
                <th>Cantidad de Alumnos</th>
            </tr>
        </thead>
        <tbody>
            {% for asignatura_info in asignaturas_con_alumnos %}
                <tr>
                    <td>{{ asignatura_info.asignatura.nombre }}</td>
                    <td>{{ asignatura_info.cantidad_alumnos }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <ul>
        <li><a href="{% url 'asignaturas_list' %}">Lista de Asignaturas</a></li>
        <li><a href="{% url 'alumnos_list' %}">Lista de Alumnos</a></li>
        <!-- Agrego el botón -->
        <a href="{% url 'agregar_alumno' %}" class="btn btn-primary">Agregar Alumno</a>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"></script>

        <!-- Agrego botón -->
        <a href="{% url 'agregar_asignatura' %}" class="btn btn-primary">Agregar Asignatura</a>
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"></script>
    </ul>
</body>
</html>